version: '3.8'

networks:
  shared-network:
    driver: bridge

services:

  db:
    container_name: asperitas_db
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - shared-network
    image: postgres:13-alpine
    ports:
      - 5432:5432      

  asperitas-api:
    container_name: asperitas-api
    networks:
      - shared-network
    image: asperitas-api-amd64:1.0
    ports:
      - 8080:8080 # CRUD API
      - 4000:4000 # DEBUG API
    depends_on:
      - db