// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

type Info interface {
	IsInfo()
}

type AuthData struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type Author struct {
	Username string `json:"username"`
	AuthorID string `json:"author_id"`
	Posts    []Info `json:"posts"`
}

type Comment struct {
	Body        string    `json:"body"`
	CommentID   string    `json:"comment_id"`
	Author      *Author   `json:"author"`
	DateCreated time.Time `json:"date_created"`
	Post        Info      `json:"post"`
}

type PostLink struct {
	PostID           string     `json:"post_id"`
	Title            string     `json:"title"`
	Type             PostType   `json:"type"`
	Score            int        `json:"score"`
	Views            int        `json:"views"`
	Category         Category   `json:"category"`
	DateCreated      time.Time  `json:"date_created"`
	UpvotePercentage int        `json:"upvote_percentage"`
	Author           *Author    `json:"author"`
	Votes            []*Vote    `json:"votes"`
	Comments         []*Comment `json:"Comments"`
	URL              string     `json:"url"`
}

func (PostLink) IsInfo() {}

type PostText struct {
	PostID           string     `json:"post_id"`
	Title            string     `json:"title"`
	Type             PostType   `json:"type"`
	Score            int        `json:"score"`
	Views            int        `json:"views"`
	Category         Category   `json:"category"`
	DateCreated      time.Time  `json:"date_created"`
	UpvotePercentage int        `json:"upvote_percentage"`
	Author           *Author    `json:"author"`
	Votes            []*Vote    `json:"votes"`
	Comments         []*Comment `json:"Comments"`
	Text             string     `json:"text"`
}

func (PostText) IsInfo() {}

type User struct {
	Username string `json:"username"`
	UserID   string `json:"user_id"`
}

type Vote struct {
	Vote     int     `json:"vote"`
	AuthorID string  `json:"author_id"`
	Author   *Author `json:"author"`
}

type Category string

const (
	CategoryAll         Category = "ALL"
	CategoryMusic       Category = "MUSIC"
	CategoryFunny       Category = "FUNNY"
	CategoryVideos      Category = "VIDEOS"
	CategoryProgramming Category = "PROGRAMMING"
	CategoryNews        Category = "NEWS"
	CategoryFashion     Category = "FASHION"
)

var AllCategory = []Category{
	CategoryAll,
	CategoryMusic,
	CategoryFunny,
	CategoryVideos,
	CategoryProgramming,
	CategoryNews,
	CategoryFashion,
}

func (e Category) IsValid() bool {
	switch e {
	case CategoryAll, CategoryMusic, CategoryFunny, CategoryVideos, CategoryProgramming, CategoryNews, CategoryFashion:
		return true
	}
	return false
}

func (e Category) String() string {
	return string(e)
}

func (e *Category) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Category(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Category", str)
	}
	return nil
}

func (e Category) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type PostType string

const (
	PostTypeLink PostType = "LINK"
	PostTypeText PostType = "TEXT"
)

var AllPostType = []PostType{
	PostTypeLink,
	PostTypeText,
}

func (e PostType) IsValid() bool {
	switch e {
	case PostTypeLink, PostTypeText:
		return true
	}
	return false
}

func (e PostType) String() string {
	return string(e)
}

func (e *PostType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PostType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PostType", str)
	}
	return nil
}

func (e PostType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
